export const getMovies = async () => {

  return [{
       "address":"Av. Guilherme Campos",
       "allImages":[
          "https://yespet.app/sites/default/files/2023-05/Screenshot%20from%202023-05-27%2019-09-19.png",
          "https://yespet.app/sites/default/files/2023-05/Parque_Dom_Pedro_Shopping_%281%29.jpg",
          "https://yespet.app/sites/default/files/2023-06/Screenshot%20from%202023-06-08%2016-21-35_0.png"
       ],
       "city":"Campinas",
       "countComment":7,
       "distance":10305,
       "facebook":"pablorigueto",
       "image":"https://yespet.app/sites/default/files/2023-05/Screenshot%20from%202023-05-27%2019-09-19.png",
       "instagram":"pablorigueto",
       "neigh":"Jardim Santa Genebra",
       "nodeid":1,
       "ntitle":"Dom Pedro Campinas-SP",
       "number":"500",
       "offerServices":{
          "__typename":"ServicesOff",
          "bathing_and_grooming":false,
          "delivery":false,
          "dog_care":true,
          "dog_trainer":false,
          "dog_walker":true,
          "food":true,
          "hotel":false,
          "petshop":false,
          "playing":false,
          "veterinary":true,
          "water":false
       },
       "pathAlias":"/en-us/dom-pedro-campinas-sp",
       "placeLat":-22.8479489,
       "placeLong":-47.06368560643477,
       "state":"SP",
       "type":"Shopping",
       "vote":2.5,
       "votes":[
          [
             "Object"
          ],
          [
             "Object"
          ]
       ],
       "website":"https://google.com.br",
       "whatsapp":"+5519995096363"
    },
    {
       "address":"Av. Brg. Faria Lima",
       "allImages":[
          "https://yespet.app/sites/default/files/2023-05/Screenshot%20from%202023-05-27%2020-09-59.png",
          "https://yespet.app/sites/default/files/2023-05/Screenshot%20from%202023-05-27%2020-10-03.png",
          "https://yespet.app/sites/default/files/2023-06/Screenshot%20from%202023-06-14%2021-05-59.png",
          "https://yespet.app/sites/default/files/2023-06/Screenshot%20from%202023-06-13%2022-16-14.png"
       ],
       "city":"São Paulo",
       "countComment":1,
       "distance":10387,
       "facebook":"",
       "image":"https://yespet.app/sites/default/files/2023-05/Screenshot%20from%202023-05-27%2020-09-59.png",
       "instagram":"",
       "neigh":"Jardim Paulistano",
       "nodeid":2,
       "ntitle":"Iguatemi São Paulo-SP",
       "number":"2232",
       "offerServices":{
          "__typename":"ServicesOff",
          "bathing_and_grooming":true,
          "delivery":false,
          "dog_care":false,
          "dog_trainer":false,
          "dog_walker":false,
          "food":false,
          "hotel":false,
          "petshop":true,
          "playing":false,
          "veterinary":false,
          "water":true
       },
       "pathAlias":"/en-us/node/2",
       "placeLat":-23.5767289,
       "placeLong":-46.6874865,
       "state":"SP",
       "type":"Shopping",
       "vote":5,
       "votes":[
          [
             "Object"
          ]
       ],
       "website":"",
       "whatsapp":"+5519191911161"
    },
    {
       "address":"Rua massaranduba",
       "allImages":[
          "https://yespet.app/sites/default/files/2023-05/Screenshot%20from%202023-05-27%2020-10-03_0.png",
          "https://yespet.app/sites/default/files/2023-06/Screenshot%20from%202023-06-08%2016-21-35.png"
       ],
       "city":"Holambra",
       "countComment":4,
       "distance":10291,
       "facebook":"pablorigueto",
       "image":"https://yespet.app/sites/default/files/2023-05/Screenshot%20from%202023-05-27%2020-10-03_0.png",
       "instagram":"pablorigueto",
       "neigh":"parque dos ipes",
       "nodeid":3,
       "ntitle":"Casa em Holambra-SP",
       "number":"38",
       "offerServices":{
          "__typename":"ServicesOff",
          "bathing_and_grooming":false,
          "delivery":false,
          "dog_care":false,
          "dog_trainer":true,
          "dog_walker":false,
          "food":false,
          "hotel":false,
          "petshop":false,
          "playing":true,
          "veterinary":false,
          "water":true
       },
       "pathAlias":"/en-us/node/3",
       "placeLat":-22.6406264,
       "placeLong":-47.0559521,
       "state":"SP",
       "type":"Hotel",
       "vote":2,
       "votes":[
          [
             "Object"
          ]
       ],
       "website":"boaerd.com",
       "whatsapp":"+5519191911161"
    },
    {
       "address":"Rua Jasmins",
       "allImages":[
          "https://yespet.app/sites/default/files/2023-06/Screenshot%20from%202023-06-21%2018-55-56.png",
          "https://yespet.app/sites/default/files/2023-06/Screenshot%20from%202023-06-21%2018-58-01.png"
       ],
       "city":"Holambra",
       "countComment":0,
       "distance":10291,
       "facebook":"pablorigueto",
       "image":"https://yespet.app/sites/default/files/2023-06/Screenshot%20from%202023-06-21%2018-55-56.png",
       "instagram":"dompedro",
       "neigh":"parque dos ipes",
       "nodeid":5,
       "ntitle":"Jasmin Gigante nome para teste de quebra xablau Jasmin Gigante nome para teste de quebra xablau",
       "number":"60",
       "offerServices":{
          "__typename":"ServicesOff",
          "bathing_and_grooming":false,
          "delivery":false,
          "dog_care":false,
          "dog_trainer":false,
          "dog_walker":false,
          "food":true,
          "hotel":false,
          "petshop":false,
          "playing":true,
          "veterinary":true,
          "water":true
       },
       "pathAlias":"/en-us/node/5",
       "placeLat":-22.6405667,
       "placeLong":-47.05534,
       "state":"SP",
       "type":"Restaurante",
       "vote":null,
       "votes":[
          
       ],
       "website":"google.com.br",
       "whatsapp":"+5519991000000"
    },
    {
       "address":"Rua Jacarandá",
       "allImages":[
          "https://yespet.app/sites/default/files/2023-06/Screenshot%20from%202023-06-21%2018-56-46.png",
          "https://yespet.app/sites/default/files/2023-06/Screenshot%20from%202023-06-21%2018-56-40.png"
       ],
       "city":"Holambra",
       "countComment":0,
       "distance":10291,
       "facebook":"pablorigueto",
       "image":"https://yespet.app/sites/default/files/2023-06/Screenshot%20from%202023-06-21%2018-56-46.png",
       "instagram":"dompedro",
       "neigh":"parque dos ipes",
       "nodeid":6,
       "ntitle":"Jacaranda title",
       "number":"87",
       "offerServices":{
          "__typename":"ServicesOff",
          "bathing_and_grooming":true,
          "delivery":true,
          "dog_care":true,
          "dog_trainer":false,
          "dog_walker":false,
          "food":true,
          "hotel":false,
          "petshop":false,
          "playing":false,
          "veterinary":false,
          "water":false
       },
       "pathAlias":"/en-us/node/6",
       "placeLat":-22.6406889,
       "placeLong":-47.0564699,
       "state":"SP",
       "type":"Pousada",
       "vote":3,
       "votes":[
          
       ],
       "website":"google.com.br",
       "whatsapp":"+5519991000000"
    },
    {
       "address":"R. Leandro Gonçalves",
       "allImages":[
          "https://yespet.app/sites/default/files/2023-06/Screenshot%20from%202023-06-21%2018-55-56_0.png",
          "https://yespet.app/sites/default/files/2023-06/Screenshot%20from%202023-06-21%2018-56-46_2.png"
       ],
       "city":"Holambra",
       "countComment":0,
       "distance":10291,
       "facebook":"pablorigueto",
       "image":"https://yespet.app/sites/default/files/2023-06/Screenshot%20from%202023-06-21%2018-55-56_0.png",
       "instagram":"",
       "neigh":"centro",
       "nodeid":9,
       "ntitle":"Dog Walker Title",
       "number":"115",
       "offerServices":{
          "__typename":"ServicesOff",
          "bathing_and_grooming":false,
          "delivery":false,
          "dog_care":false,
          "dog_trainer":false,
          "dog_walker":true,
          "food":true,
          "hotel":true,
          "petshop":true,
          "playing":false,
          "veterinary":false,
          "water":false
       },
       "pathAlias":"/en-us/node/9",
       "placeLat":-22.634955,
       "placeLong":-47.0557473,
       "state":"SP",
       "type":"DW",
       "vote":5,
       "votes":[
          
       ],
       "website":"yespet.app",
       "whatsapp":"+5519991000000"
    },
    {
       "address":"Rua das Azaléias",
       "allImages":[
          "https://yespet.app/sites/default/files/2023-06/Screenshot%20from%202023-06-21%2018-56-40_0.png",
          "https://yespet.app/sites/default/files/2023-06/Screenshot%20from%202023-06-21%2018-56-40_1.png"
       ],
       "city":"Holambra",
       "countComment":0,
       "distance":10291,
       "facebook":"",
       "image":"https://yespet.app/sites/default/files/2023-06/Screenshot%20from%202023-06-21%2018-56-40_0.png",
       "instagram":"dompedro",
       "neigh":"Morada das Flores",
       "nodeid":10,
       "ntitle":"ONG Title",
       "number":"523",
       "offerServices":{
          "__typename":"ServicesOff",
          "bathing_and_grooming":true,
          "delivery":true,
          "dog_care":true,
          "dog_trainer":true,
          "dog_walker":true,
          "food":true,
          "hotel":true,
          "petshop":true,
          "playing":true,
          "veterinary":true,
          "water":true
       },
       "pathAlias":"/en-us/node/10",
       "placeLat":-22.6403808,
       "placeLong":-47.0535192,
       "state":"SP",
       "type":"ONG",
       "vote":3,
       "votes":[
          
       ],
       "website":"google.com.br",
       "whatsapp":"+5519991000000"
    }
 ];
};
